// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: packets.proto

package sigma_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Human struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
}

func (x *Human) Reset() {
	*x = Human{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Human) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Human) ProtoMessage() {}

func (x *Human) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Human.ProtoReflect.Descriptor instead.
func (*Human) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *Human) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Human) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Human) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Human) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type Pending struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email      string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	VerifyCode string `protobuf:"bytes,3,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
	ClientCode string `protobuf:"bytes,4,opt,name=clientCode,proto3" json:"clientCode,omitempty"`
	State      string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Pending) Reset() {
	*x = Pending{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pending) ProtoMessage() {}

func (x *Pending) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pending.ProtoReflect.Descriptor instead.
func (*Pending) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *Pending) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pending) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Pending) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *Pending) GetClientCode() string {
	if x != nil {
		return x.ClientCode
	}
	return ""
}

func (x *Pending) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	CreatureType int32  `protobuf:"varint,3,opt,name=creatureType,proto3" json:"creatureType,omitempty"`
	Token        string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Session) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Session) GetCreatureType() int32 {
	if x != nil {
		return x.CreatureType
	}
	return 0
}

func (x *Session) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HumanSignupDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *HumanSignupDto) Reset() {
	*x = HumanSignupDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanSignupDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanSignupDto) ProtoMessage() {}

func (x *HumanSignupDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanSignupDto.ProtoReflect.Descriptor instead.
func (*HumanSignupDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *HumanSignupDto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type HumanSignupOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pending *Pending `protobuf:"bytes,1,opt,name=pending,proto3" json:"pending,omitempty"`
}

func (x *HumanSignupOutput) Reset() {
	*x = HumanSignupOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanSignupOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanSignupOutput) ProtoMessage() {}

func (x *HumanSignupOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanSignupOutput.ProtoReflect.Descriptor instead.
func (*HumanSignupOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *HumanSignupOutput) GetPending() *Pending {
	if x != nil {
		return x.Pending
	}
	return nil
}

type HumanVerifyDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerifyCode string `protobuf:"bytes,1,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
	ClientCode string `protobuf:"bytes,2,opt,name=clientCode,proto3" json:"clientCode,omitempty"`
}

func (x *HumanVerifyDto) Reset() {
	*x = HumanVerifyDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanVerifyDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanVerifyDto) ProtoMessage() {}

func (x *HumanVerifyDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanVerifyDto.ProtoReflect.Descriptor instead.
func (*HumanVerifyDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

func (x *HumanVerifyDto) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *HumanVerifyDto) GetClientCode() string {
	if x != nil {
		return x.ClientCode
	}
	return ""
}

type HumanVerifyOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pending *Pending `protobuf:"bytes,1,opt,name=pending,proto3" json:"pending,omitempty"`
	Human   *Human   `protobuf:"bytes,2,opt,name=human,proto3" json:"human,omitempty"`
	Session *Session `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *HumanVerifyOutput) Reset() {
	*x = HumanVerifyOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanVerifyOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanVerifyOutput) ProtoMessage() {}

func (x *HumanVerifyOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanVerifyOutput.ProtoReflect.Descriptor instead.
func (*HumanVerifyOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

func (x *HumanVerifyOutput) GetPending() *Pending {
	if x != nil {
		return x.Pending
	}
	return nil
}

func (x *HumanVerifyOutput) GetHuman() *Human {
	if x != nil {
		return x.Human
	}
	return nil
}

func (x *HumanVerifyOutput) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type HumanCompleteDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerifyCode string `protobuf:"bytes,1,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
	ClientCode string `protobuf:"bytes,2,opt,name=clientCode,proto3" json:"clientCode,omitempty"`
	FirstName  string `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName   string `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
}

func (x *HumanCompleteDto) Reset() {
	*x = HumanCompleteDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanCompleteDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanCompleteDto) ProtoMessage() {}

func (x *HumanCompleteDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanCompleteDto.ProtoReflect.Descriptor instead.
func (*HumanCompleteDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

func (x *HumanCompleteDto) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *HumanCompleteDto) GetClientCode() string {
	if x != nil {
		return x.ClientCode
	}
	return ""
}

func (x *HumanCompleteDto) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *HumanCompleteDto) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type HumanCompleteOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Human   *Human   `protobuf:"bytes,2,opt,name=human,proto3" json:"human,omitempty"`
	Session *Session `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *HumanCompleteOutput) Reset() {
	*x = HumanCompleteOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanCompleteOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanCompleteOutput) ProtoMessage() {}

func (x *HumanCompleteOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanCompleteOutput.ProtoReflect.Descriptor instead.
func (*HumanCompleteOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *HumanCompleteOutput) GetHuman() *Human {
	if x != nil {
		return x.Human
	}
	return nil
}

func (x *HumanCompleteOutput) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type HumanUpdateDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
}

func (x *HumanUpdateDto) Reset() {
	*x = HumanUpdateDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanUpdateDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanUpdateDto) ProtoMessage() {}

func (x *HumanUpdateDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanUpdateDto.ProtoReflect.Descriptor instead.
func (*HumanUpdateDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{9}
}

func (x *HumanUpdateDto) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *HumanUpdateDto) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type HumanUpdateOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Human *Human `protobuf:"bytes,1,opt,name=human,proto3" json:"human,omitempty"`
}

func (x *HumanUpdateOutput) Reset() {
	*x = HumanUpdateOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanUpdateOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanUpdateOutput) ProtoMessage() {}

func (x *HumanUpdateOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanUpdateOutput.ProtoReflect.Descriptor instead.
func (*HumanUpdateOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{10}
}

func (x *HumanUpdateOutput) GetHuman() *Human {
	if x != nil {
		return x.Human
	}
	return nil
}

type HumanGetDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *HumanGetDto) Reset() {
	*x = HumanGetDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanGetDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanGetDto) ProtoMessage() {}

func (x *HumanGetDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanGetDto.ProtoReflect.Descriptor instead.
func (*HumanGetDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{11}
}

func (x *HumanGetDto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type HumanGetOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Human *Human `protobuf:"bytes,1,opt,name=human,proto3" json:"human,omitempty"`
}

func (x *HumanGetOutput) Reset() {
	*x = HumanGetOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanGetOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanGetOutput) ProtoMessage() {}

func (x *HumanGetOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanGetOutput.ProtoReflect.Descriptor instead.
func (*HumanGetOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{12}
}

func (x *HumanGetOutput) GetHuman() *Human {
	if x != nil {
		return x.Human
	}
	return nil
}

type Tower struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarId  int64  `protobuf:"varint,3,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	IsPublic  bool   `protobuf:"varint,4,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
	CreatorId int64  `protobuf:"varint,5,opt,name=creatorId,proto3" json:"creatorId,omitempty"`
}

func (x *Tower) Reset() {
	*x = Tower{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tower) ProtoMessage() {}

func (x *Tower) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tower.ProtoReflect.Descriptor instead.
func (*Tower) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{13}
}

func (x *Tower) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tower) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tower) GetAvatarId() int64 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *Tower) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

func (x *Tower) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

type Member struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	HumanId int64 `protobuf:"varint,2,opt,name=humanId,proto3" json:"humanId,omitempty"`
	TowerId int64 `protobuf:"varint,3,opt,name=towerId,proto3" json:"towerId,omitempty"`
}

func (x *Member) Reset() {
	*x = Member{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{14}
}

func (x *Member) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Member) GetHumanId() int64 {
	if x != nil {
		return x.HumanId
	}
	return 0
}

func (x *Member) GetTowerId() int64 {
	if x != nil {
		return x.TowerId
	}
	return 0
}

type TowerCreateDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AvatarId int64  `protobuf:"varint,2,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	IsPublic bool   `protobuf:"varint,3,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
}

func (x *TowerCreateDto) Reset() {
	*x = TowerCreateDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TowerCreateDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowerCreateDto) ProtoMessage() {}

func (x *TowerCreateDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowerCreateDto.ProtoReflect.Descriptor instead.
func (*TowerCreateDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{15}
}

func (x *TowerCreateDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TowerCreateDto) GetAvatarId() int64 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *TowerCreateDto) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type TowerCreateOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tower  *Tower  `protobuf:"bytes,1,opt,name=tower,proto3" json:"tower,omitempty"`
	Member *Member `protobuf:"bytes,2,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *TowerCreateOutput) Reset() {
	*x = TowerCreateOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TowerCreateOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowerCreateOutput) ProtoMessage() {}

func (x *TowerCreateOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowerCreateOutput.ProtoReflect.Descriptor instead.
func (*TowerCreateOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{16}
}

func (x *TowerCreateOutput) GetTower() *Tower {
	if x != nil {
		return x.Tower
	}
	return nil
}

func (x *TowerCreateOutput) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

type TowerUpdateDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TowerId  int64  `protobuf:"varint,1,opt,name=towerId,proto3" json:"towerId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarId int64  `protobuf:"varint,3,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	IsPublic bool   `protobuf:"varint,4,opt,name=isPublic,proto3" json:"isPublic,omitempty"`
}

func (x *TowerUpdateDto) Reset() {
	*x = TowerUpdateDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TowerUpdateDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowerUpdateDto) ProtoMessage() {}

func (x *TowerUpdateDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowerUpdateDto.ProtoReflect.Descriptor instead.
func (*TowerUpdateDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{17}
}

func (x *TowerUpdateDto) GetTowerId() int64 {
	if x != nil {
		return x.TowerId
	}
	return 0
}

func (x *TowerUpdateDto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TowerUpdateDto) GetAvatarId() int64 {
	if x != nil {
		return x.AvatarId
	}
	return 0
}

func (x *TowerUpdateDto) GetIsPublic() bool {
	if x != nil {
		return x.IsPublic
	}
	return false
}

type TowerUpdateOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tower *Tower `protobuf:"bytes,1,opt,name=tower,proto3" json:"tower,omitempty"`
}

func (x *TowerUpdateOutput) Reset() {
	*x = TowerUpdateOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TowerUpdateOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowerUpdateOutput) ProtoMessage() {}

func (x *TowerUpdateOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowerUpdateOutput.ProtoReflect.Descriptor instead.
func (*TowerUpdateOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{18}
}

func (x *TowerUpdateOutput) GetTower() *Tower {
	if x != nil {
		return x.Tower
	}
	return nil
}

type TowerDeleteDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TowerId int64 `protobuf:"varint,1,opt,name=towerId,proto3" json:"towerId,omitempty"`
}

func (x *TowerDeleteDto) Reset() {
	*x = TowerDeleteDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TowerDeleteDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowerDeleteDto) ProtoMessage() {}

func (x *TowerDeleteDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowerDeleteDto.ProtoReflect.Descriptor instead.
func (*TowerDeleteDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{19}
}

func (x *TowerDeleteDto) GetTowerId() int64 {
	if x != nil {
		return x.TowerId
	}
	return 0
}

type TowerDeleteOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TowerDeleteOutput) Reset() {
	*x = TowerDeleteOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TowerDeleteOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowerDeleteOutput) ProtoMessage() {}

func (x *TowerDeleteOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowerDeleteOutput.ProtoReflect.Descriptor instead.
func (*TowerDeleteOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{20}
}

type TowerGetDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TowerId string `protobuf:"bytes,1,opt,name=towerId,proto3" json:"towerId,omitempty"`
}

func (x *TowerGetDto) Reset() {
	*x = TowerGetDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TowerGetDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowerGetDto) ProtoMessage() {}

func (x *TowerGetDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowerGetDto.ProtoReflect.Descriptor instead.
func (*TowerGetDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{21}
}

func (x *TowerGetDto) GetTowerId() string {
	if x != nil {
		return x.TowerId
	}
	return ""
}

type TowerGetOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tower *Tower `protobuf:"bytes,1,opt,name=tower,proto3" json:"tower,omitempty"`
}

func (x *TowerGetOutput) Reset() {
	*x = TowerGetOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TowerGetOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowerGetOutput) ProtoMessage() {}

func (x *TowerGetOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowerGetOutput.ProtoReflect.Descriptor instead.
func (*TowerGetOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{22}
}

func (x *TowerGetOutput) GetTower() *Tower {
	if x != nil {
		return x.Tower
	}
	return nil
}

type TowerJoinDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TowerId string `protobuf:"bytes,1,opt,name=towerId,proto3" json:"towerId,omitempty"`
}

func (x *TowerJoinDto) Reset() {
	*x = TowerJoinDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TowerJoinDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowerJoinDto) ProtoMessage() {}

func (x *TowerJoinDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowerJoinDto.ProtoReflect.Descriptor instead.
func (*TowerJoinDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{23}
}

func (x *TowerJoinDto) GetTowerId() string {
	if x != nil {
		return x.TowerId
	}
	return ""
}

type TowerJoinOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member *Member `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
}

func (x *TowerJoinOutput) Reset() {
	*x = TowerJoinOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TowerJoinOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TowerJoinOutput) ProtoMessage() {}

func (x *TowerJoinOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TowerJoinOutput.ProtoReflect.Descriptor instead.
func (*TowerJoinOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{24}
}

func (x *TowerJoinOutput) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

var File_packets_proto protoreflect.FileDescriptor

var file_packets_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x22, 0x67, 0x0a, 0x05, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x85, 0x01, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x6b, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x26, 0x0a, 0x0e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x53, 0x69, 0x67,
	0x6e, 0x75, 0x70, 0x44, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x3d, 0x0a, 0x11,
	0x48, 0x75, 0x6d, 0x61, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x28, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x50, 0x0a, 0x0e, 0x48,
	0x75, 0x6d, 0x61, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x44, 0x74, 0x6f, 0x12, 0x1e, 0x0a,
	0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x8b, 0x01,
	0x0a, 0x11, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x50, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a,
	0x05, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73,
	0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x52, 0x05, 0x68, 0x75, 0x6d, 0x61,
	0x6e, 0x12, 0x28, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x8c, 0x01, 0x0a, 0x10,
	0x48, 0x75, 0x6d, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x74, 0x6f,
	0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x63, 0x0a, 0x13, 0x48, 0x75,
	0x6d, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x22, 0x0a, 0x05, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x52, 0x05,
	0x68, 0x75, 0x6d, 0x61, 0x6e, 0x12, 0x28, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x4a, 0x0a, 0x0e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x74,
	0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x11, 0x48,
	0x75, 0x6d, 0x61, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x22, 0x0a, 0x05, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x52, 0x05, 0x68,
	0x75, 0x6d, 0x61, 0x6e, 0x22, 0x25, 0x0a, 0x0b, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x47, 0x65, 0x74,
	0x44, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x0e, 0x48,
	0x75, 0x6d, 0x61, 0x6e, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x22, 0x0a,
	0x05, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73,
	0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x52, 0x05, 0x68, 0x75, 0x6d, 0x61,
	0x6e, 0x22, 0x81, 0x01, 0x0a, 0x05, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x6f, 0x72, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x06, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x07, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x77,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x6f, 0x77, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x5c, 0x0a, 0x0e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x74, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x22, 0x5e, 0x0a, 0x11, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x54, 0x6f,
	0x77, 0x65, 0x72, 0x52, 0x05, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x06, 0x6d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x69, 0x67,
	0x6d, 0x61, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65,
	0x72, 0x22, 0x76, 0x0a, 0x0e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x44, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x22, 0x37, 0x0a, 0x11, 0x54, 0x6f, 0x77,
	0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x22,
	0x0a, 0x05, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x05, 0x74, 0x6f, 0x77,
	0x65, 0x72, 0x22, 0x2a, 0x0a, 0x0e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x44, 0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x22, 0x13,
	0x0a, 0x11, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x22, 0x27, 0x0a, 0x0b, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x47, 0x65, 0x74, 0x44,
	0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x0e,
	0x54, 0x6f, 0x77, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x22,
	0x0a, 0x05, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x05, 0x74, 0x6f, 0x77,
	0x65, 0x72, 0x22, 0x28, 0x0a, 0x0c, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x44,
	0x74, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x77, 0x65, 0x72, 0x49, 0x64, 0x22, 0x38, 0x0a, 0x0f,
	0x54, 0x6f, 0x77, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12,
	0x25, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06,
	0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x32, 0xbc, 0x02, 0x0a, 0x0c, 0x48, 0x75, 0x6d, 0x61, 0x6e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x75,
	0x70, 0x12, 0x15, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x53,
	0x69, 0x67, 0x6e, 0x75, 0x70, 0x44, 0x74, 0x6f, 0x1a, 0x18, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61,
	0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x15,
	0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x44, 0x74, 0x6f, 0x1a, 0x18, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75,
	0x6d, 0x61, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22,
	0x00, 0x12, 0x41, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x17, 0x2e,
	0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x1a, 0x1a, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48,
	0x75, 0x6d, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x15,
	0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x74, 0x6f, 0x1a, 0x18, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75,
	0x6d, 0x61, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22,
	0x00, 0x12, 0x32, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61,
	0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x47, 0x65, 0x74, 0x44, 0x74, 0x6f, 0x1a, 0x15, 0x2e, 0x73,
	0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x22, 0x00, 0x32, 0xb0, 0x02, 0x0a, 0x0c, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x15, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f, 0x1a, 0x18, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e,
	0x54, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e,
	0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x44, 0x74, 0x6f, 0x1a, 0x18, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x54, 0x6f, 0x77,
	0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00,
	0x12, 0x3b, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x73, 0x69, 0x67,
	0x6d, 0x61, 0x2e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x74,
	0x6f, 0x1a, 0x18, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x12, 0x32, 0x0a,
	0x03, 0x67, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x54, 0x6f, 0x77,
	0x65, 0x72, 0x47, 0x65, 0x74, 0x44, 0x74, 0x6f, 0x1a, 0x15, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61,
	0x2e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22,
	0x00, 0x12, 0x35, 0x0a, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x12, 0x13, 0x2e, 0x73, 0x69, 0x67, 0x6d,
	0x61, 0x2e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e, 0x44, 0x74, 0x6f, 0x1a, 0x16,
	0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x54, 0x6f, 0x77, 0x65, 0x72, 0x4a, 0x6f, 0x69, 0x6e,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x42, 0x40, 0x0a, 0x0d, 0x69, 0x6f, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x42, 0x0a, 0x53, 0x69, 0x67, 0x6d, 0x61,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x73, 0x69, 0x67, 0x6d, 0x61, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData = file_packets_proto_rawDesc
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(file_packets_proto_rawDescData)
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_packets_proto_goTypes = []interface{}{
	(*Human)(nil),               // 0: sigma.Human
	(*Pending)(nil),             // 1: sigma.Pending
	(*Session)(nil),             // 2: sigma.Session
	(*HumanSignupDto)(nil),      // 3: sigma.HumanSignupDto
	(*HumanSignupOutput)(nil),   // 4: sigma.HumanSignupOutput
	(*HumanVerifyDto)(nil),      // 5: sigma.HumanVerifyDto
	(*HumanVerifyOutput)(nil),   // 6: sigma.HumanVerifyOutput
	(*HumanCompleteDto)(nil),    // 7: sigma.HumanCompleteDto
	(*HumanCompleteOutput)(nil), // 8: sigma.HumanCompleteOutput
	(*HumanUpdateDto)(nil),      // 9: sigma.HumanUpdateDto
	(*HumanUpdateOutput)(nil),   // 10: sigma.HumanUpdateOutput
	(*HumanGetDto)(nil),         // 11: sigma.HumanGetDto
	(*HumanGetOutput)(nil),      // 12: sigma.HumanGetOutput
	(*Tower)(nil),               // 13: sigma.Tower
	(*Member)(nil),              // 14: sigma.Member
	(*TowerCreateDto)(nil),      // 15: sigma.TowerCreateDto
	(*TowerCreateOutput)(nil),   // 16: sigma.TowerCreateOutput
	(*TowerUpdateDto)(nil),      // 17: sigma.TowerUpdateDto
	(*TowerUpdateOutput)(nil),   // 18: sigma.TowerUpdateOutput
	(*TowerDeleteDto)(nil),      // 19: sigma.TowerDeleteDto
	(*TowerDeleteOutput)(nil),   // 20: sigma.TowerDeleteOutput
	(*TowerGetDto)(nil),         // 21: sigma.TowerGetDto
	(*TowerGetOutput)(nil),      // 22: sigma.TowerGetOutput
	(*TowerJoinDto)(nil),        // 23: sigma.TowerJoinDto
	(*TowerJoinOutput)(nil),     // 24: sigma.TowerJoinOutput
}
var file_packets_proto_depIdxs = []int32{
	1,  // 0: sigma.HumanSignupOutput.pending:type_name -> sigma.Pending
	1,  // 1: sigma.HumanVerifyOutput.pending:type_name -> sigma.Pending
	0,  // 2: sigma.HumanVerifyOutput.human:type_name -> sigma.Human
	2,  // 3: sigma.HumanVerifyOutput.session:type_name -> sigma.Session
	0,  // 4: sigma.HumanCompleteOutput.human:type_name -> sigma.Human
	2,  // 5: sigma.HumanCompleteOutput.session:type_name -> sigma.Session
	0,  // 6: sigma.HumanUpdateOutput.human:type_name -> sigma.Human
	0,  // 7: sigma.HumanGetOutput.human:type_name -> sigma.Human
	13, // 8: sigma.TowerCreateOutput.tower:type_name -> sigma.Tower
	14, // 9: sigma.TowerCreateOutput.member:type_name -> sigma.Member
	13, // 10: sigma.TowerUpdateOutput.tower:type_name -> sigma.Tower
	13, // 11: sigma.TowerGetOutput.tower:type_name -> sigma.Tower
	14, // 12: sigma.TowerJoinOutput.member:type_name -> sigma.Member
	3,  // 13: sigma.HumanService.signup:input_type -> sigma.HumanSignupDto
	5,  // 14: sigma.HumanService.verify:input_type -> sigma.HumanVerifyDto
	7,  // 15: sigma.HumanService.complete:input_type -> sigma.HumanCompleteDto
	9,  // 16: sigma.HumanService.update:input_type -> sigma.HumanUpdateDto
	11, // 17: sigma.HumanService.get:input_type -> sigma.HumanGetDto
	15, // 18: sigma.TowerService.create:input_type -> sigma.TowerCreateDto
	17, // 19: sigma.TowerService.update:input_type -> sigma.TowerUpdateDto
	19, // 20: sigma.TowerService.delete:input_type -> sigma.TowerDeleteDto
	21, // 21: sigma.TowerService.get:input_type -> sigma.TowerGetDto
	23, // 22: sigma.TowerService.join:input_type -> sigma.TowerJoinDto
	4,  // 23: sigma.HumanService.signup:output_type -> sigma.HumanSignupOutput
	6,  // 24: sigma.HumanService.verify:output_type -> sigma.HumanVerifyOutput
	8,  // 25: sigma.HumanService.complete:output_type -> sigma.HumanCompleteOutput
	10, // 26: sigma.HumanService.update:output_type -> sigma.HumanUpdateOutput
	12, // 27: sigma.HumanService.get:output_type -> sigma.HumanGetOutput
	16, // 28: sigma.TowerService.create:output_type -> sigma.TowerCreateOutput
	18, // 29: sigma.TowerService.update:output_type -> sigma.TowerUpdateOutput
	20, // 30: sigma.TowerService.delete:output_type -> sigma.TowerDeleteOutput
	22, // 31: sigma.TowerService.get:output_type -> sigma.TowerGetOutput
	24, // 32: sigma.TowerService.join:output_type -> sigma.TowerJoinOutput
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Human); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pending); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanSignupDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanSignupOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanVerifyDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanVerifyOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanCompleteDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanCompleteOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanUpdateDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanUpdateOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanGetDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanGetOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tower); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Member); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TowerCreateDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TowerCreateOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TowerUpdateDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TowerUpdateOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TowerDeleteDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TowerDeleteOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TowerGetDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TowerGetOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TowerJoinDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TowerJoinOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_rawDesc = nil
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
