// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: packets.proto

package sigma_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HumanServiceClient is the client API for HumanService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HumanServiceClient interface {
	Signup(ctx context.Context, in *SignupDto, opts ...grpc.CallOption) (*SignupOutput, error)
	Verify(ctx context.Context, in *VerifyDto, opts ...grpc.CallOption) (*VerifyOutput, error)
	Complete(ctx context.Context, in *CompleteDto, opts ...grpc.CallOption) (*CompleteOutput, error)
	Update(ctx context.Context, in *UpdateDto, opts ...grpc.CallOption) (*UpdateOutput, error)
	Get(ctx context.Context, in *GetDto, opts ...grpc.CallOption) (*GetOutput, error)
}

type humanServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHumanServiceClient(cc grpc.ClientConnInterface) HumanServiceClient {
	return &humanServiceClient{cc}
}

func (c *humanServiceClient) Signup(ctx context.Context, in *SignupDto, opts ...grpc.CallOption) (*SignupOutput, error) {
	out := new(SignupOutput)
	err := c.cc.Invoke(ctx, "/sigma.HumanService/signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *humanServiceClient) Verify(ctx context.Context, in *VerifyDto, opts ...grpc.CallOption) (*VerifyOutput, error) {
	out := new(VerifyOutput)
	err := c.cc.Invoke(ctx, "/sigma.HumanService/verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *humanServiceClient) Complete(ctx context.Context, in *CompleteDto, opts ...grpc.CallOption) (*CompleteOutput, error) {
	out := new(CompleteOutput)
	err := c.cc.Invoke(ctx, "/sigma.HumanService/complete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *humanServiceClient) Update(ctx context.Context, in *UpdateDto, opts ...grpc.CallOption) (*UpdateOutput, error) {
	out := new(UpdateOutput)
	err := c.cc.Invoke(ctx, "/sigma.HumanService/update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *humanServiceClient) Get(ctx context.Context, in *GetDto, opts ...grpc.CallOption) (*GetOutput, error) {
	out := new(GetOutput)
	err := c.cc.Invoke(ctx, "/sigma.HumanService/get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HumanServiceServer is the server API for HumanService service.
// All implementations must embed UnimplementedHumanServiceServer
// for forward compatibility
type HumanServiceServer interface {
	Signup(context.Context, *SignupDto) (*SignupOutput, error)
	Verify(context.Context, *VerifyDto) (*VerifyOutput, error)
	Complete(context.Context, *CompleteDto) (*CompleteOutput, error)
	Update(context.Context, *UpdateDto) (*UpdateOutput, error)
	Get(context.Context, *GetDto) (*GetOutput, error)
	mustEmbedUnimplementedHumanServiceServer()
}

// UnimplementedHumanServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHumanServiceServer struct {
}

func (UnimplementedHumanServiceServer) Signup(context.Context, *SignupDto) (*SignupOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedHumanServiceServer) Verify(context.Context, *VerifyDto) (*VerifyOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedHumanServiceServer) Complete(context.Context, *CompleteDto) (*CompleteOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedHumanServiceServer) Update(context.Context, *UpdateDto) (*UpdateOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedHumanServiceServer) Get(context.Context, *GetDto) (*GetOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedHumanServiceServer) mustEmbedUnimplementedHumanServiceServer() {}

// UnsafeHumanServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HumanServiceServer will
// result in compilation errors.
type UnsafeHumanServiceServer interface {
	mustEmbedUnimplementedHumanServiceServer()
}

func RegisterHumanServiceServer(s grpc.ServiceRegistrar, srv HumanServiceServer) {
	s.RegisterService(&HumanService_ServiceDesc, srv)
}

func _HumanService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sigma.HumanService/signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanServiceServer).Signup(ctx, req.(*SignupDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _HumanService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sigma.HumanService/verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanServiceServer).Verify(ctx, req.(*VerifyDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _HumanService_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanServiceServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sigma.HumanService/complete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanServiceServer).Complete(ctx, req.(*CompleteDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _HumanService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sigma.HumanService/update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanServiceServer).Update(ctx, req.(*UpdateDto))
	}
	return interceptor(ctx, in, info, handler)
}

func _HumanService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HumanServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sigma.HumanService/get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HumanServiceServer).Get(ctx, req.(*GetDto))
	}
	return interceptor(ctx, in, info, handler)
}

// HumanService_ServiceDesc is the grpc.ServiceDesc for HumanService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HumanService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sigma.HumanService",
	HandlerType: (*HumanServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "signup",
			Handler:    _HumanService_Signup_Handler,
		},
		{
			MethodName: "verify",
			Handler:    _HumanService_Verify_Handler,
		},
		{
			MethodName: "complete",
			Handler:    _HumanService_Complete_Handler,
		},
		{
			MethodName: "update",
			Handler:    _HumanService_Update_Handler,
		},
		{
			MethodName: "get",
			Handler:    _HumanService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "packets.proto",
}
