// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: packets.proto

package sigma_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Human struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName string `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
}

func (x *Human) Reset() {
	*x = Human{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Human) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Human) ProtoMessage() {}

func (x *Human) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Human.ProtoReflect.Descriptor instead.
func (*Human) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *Human) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Human) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Human) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Human) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type Pending struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email      string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	VerifyCode string `protobuf:"bytes,3,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
	ClientCode string `protobuf:"bytes,4,opt,name=clientCode,proto3" json:"clientCode,omitempty"`
	State      string `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *Pending) Reset() {
	*x = Pending{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pending) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pending) ProtoMessage() {}

func (x *Pending) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pending.ProtoReflect.Descriptor instead.
func (*Pending) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *Pending) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pending) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Pending) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *Pending) GetClientCode() string {
	if x != nil {
		return x.ClientCode
	}
	return ""
}

func (x *Pending) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type Session struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId       int64  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	CreatureType int32  `protobuf:"varint,3,opt,name=creatureType,proto3" json:"creatureType,omitempty"`
	Token        string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *Session) Reset() {
	*x = Session{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *Session) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Session) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Session) GetCreatureType() int32 {
	if x != nil {
		return x.CreatureType
	}
	return 0
}

func (x *Session) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HumanSignupDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *HumanSignupDto) Reset() {
	*x = HumanSignupDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanSignupDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanSignupDto) ProtoMessage() {}

func (x *HumanSignupDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanSignupDto.ProtoReflect.Descriptor instead.
func (*HumanSignupDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *HumanSignupDto) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type HumanSignupOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pending *Pending `protobuf:"bytes,1,opt,name=pending,proto3" json:"pending,omitempty"`
}

func (x *HumanSignupOutput) Reset() {
	*x = HumanSignupOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanSignupOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanSignupOutput) ProtoMessage() {}

func (x *HumanSignupOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanSignupOutput.ProtoReflect.Descriptor instead.
func (*HumanSignupOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

func (x *HumanSignupOutput) GetPending() *Pending {
	if x != nil {
		return x.Pending
	}
	return nil
}

type HumanVerifyDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerifyCode string `protobuf:"bytes,1,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
	ClientCode string `protobuf:"bytes,2,opt,name=clientCode,proto3" json:"clientCode,omitempty"`
}

func (x *HumanVerifyDto) Reset() {
	*x = HumanVerifyDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanVerifyDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanVerifyDto) ProtoMessage() {}

func (x *HumanVerifyDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanVerifyDto.ProtoReflect.Descriptor instead.
func (*HumanVerifyDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

func (x *HumanVerifyDto) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *HumanVerifyDto) GetClientCode() string {
	if x != nil {
		return x.ClientCode
	}
	return ""
}

type HumanVerifyOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pending *Pending `protobuf:"bytes,1,opt,name=pending,proto3" json:"pending,omitempty"`
	Human   *Human   `protobuf:"bytes,2,opt,name=human,proto3" json:"human,omitempty"`
	Session *Session `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *HumanVerifyOutput) Reset() {
	*x = HumanVerifyOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanVerifyOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanVerifyOutput) ProtoMessage() {}

func (x *HumanVerifyOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanVerifyOutput.ProtoReflect.Descriptor instead.
func (*HumanVerifyOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

func (x *HumanVerifyOutput) GetPending() *Pending {
	if x != nil {
		return x.Pending
	}
	return nil
}

func (x *HumanVerifyOutput) GetHuman() *Human {
	if x != nil {
		return x.Human
	}
	return nil
}

func (x *HumanVerifyOutput) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type HumanCompleteDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VerifyCode string `protobuf:"bytes,1,opt,name=verifyCode,proto3" json:"verifyCode,omitempty"`
	ClientCode string `protobuf:"bytes,2,opt,name=clientCode,proto3" json:"clientCode,omitempty"`
	FirstName  string `protobuf:"bytes,3,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName   string `protobuf:"bytes,4,opt,name=lastName,proto3" json:"lastName,omitempty"`
}

func (x *HumanCompleteDto) Reset() {
	*x = HumanCompleteDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanCompleteDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanCompleteDto) ProtoMessage() {}

func (x *HumanCompleteDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanCompleteDto.ProtoReflect.Descriptor instead.
func (*HumanCompleteDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

func (x *HumanCompleteDto) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *HumanCompleteDto) GetClientCode() string {
	if x != nil {
		return x.ClientCode
	}
	return ""
}

func (x *HumanCompleteDto) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *HumanCompleteDto) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type HumanCompleteOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Human   *Human   `protobuf:"bytes,2,opt,name=human,proto3" json:"human,omitempty"`
	Session *Session `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
}

func (x *HumanCompleteOutput) Reset() {
	*x = HumanCompleteOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanCompleteOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanCompleteOutput) ProtoMessage() {}

func (x *HumanCompleteOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanCompleteOutput.ProtoReflect.Descriptor instead.
func (*HumanCompleteOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *HumanCompleteOutput) GetHuman() *Human {
	if x != nil {
		return x.Human
	}
	return nil
}

func (x *HumanCompleteOutput) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type HumanUpdateDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName  string `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
}

func (x *HumanUpdateDto) Reset() {
	*x = HumanUpdateDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanUpdateDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanUpdateDto) ProtoMessage() {}

func (x *HumanUpdateDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanUpdateDto.ProtoReflect.Descriptor instead.
func (*HumanUpdateDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{9}
}

func (x *HumanUpdateDto) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *HumanUpdateDto) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type HumanUpdateOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Human *Human `protobuf:"bytes,1,opt,name=human,proto3" json:"human,omitempty"`
}

func (x *HumanUpdateOutput) Reset() {
	*x = HumanUpdateOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanUpdateOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanUpdateOutput) ProtoMessage() {}

func (x *HumanUpdateOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanUpdateOutput.ProtoReflect.Descriptor instead.
func (*HumanUpdateOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{10}
}

func (x *HumanUpdateOutput) GetHuman() *Human {
	if x != nil {
		return x.Human
	}
	return nil
}

type HumanGetDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *HumanGetDto) Reset() {
	*x = HumanGetDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanGetDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanGetDto) ProtoMessage() {}

func (x *HumanGetDto) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanGetDto.ProtoReflect.Descriptor instead.
func (*HumanGetDto) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{11}
}

func (x *HumanGetDto) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type HumanGetOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Human *Human `protobuf:"bytes,1,opt,name=human,proto3" json:"human,omitempty"`
}

func (x *HumanGetOutput) Reset() {
	*x = HumanGetOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_packets_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HumanGetOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HumanGetOutput) ProtoMessage() {}

func (x *HumanGetOutput) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HumanGetOutput.ProtoReflect.Descriptor instead.
func (*HumanGetOutput) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{12}
}

func (x *HumanGetOutput) GetHuman() *Human {
	if x != nil {
		return x.Human
	}
	return nil
}

var File_packets_proto protoreflect.FileDescriptor

var file_packets_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x22, 0x67, 0x0a, 0x05, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x85, 0x01, 0x0a, 0x07, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x6b, 0x0a, 0x07, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x26, 0x0a, 0x0e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x53, 0x69, 0x67,
	0x6e, 0x75, 0x70, 0x44, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x3d, 0x0a, 0x11,
	0x48, 0x75, 0x6d, 0x61, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x28, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x50, 0x0a, 0x0e, 0x48,
	0x75, 0x6d, 0x61, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x44, 0x74, 0x6f, 0x12, 0x1e, 0x0a,
	0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x8b, 0x01,
	0x0a, 0x11, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x50, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x22, 0x0a,
	0x05, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73,
	0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x52, 0x05, 0x68, 0x75, 0x6d, 0x61,
	0x6e, 0x12, 0x28, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x8c, 0x01, 0x0a, 0x10,
	0x48, 0x75, 0x6d, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x74, 0x6f,
	0x12, 0x1e, 0x0a, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x63, 0x0a, 0x13, 0x48, 0x75,
	0x6d, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x12, 0x22, 0x0a, 0x05, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x52, 0x05,
	0x68, 0x75, 0x6d, 0x61, 0x6e, 0x12, 0x28, 0x0a, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22,
	0x4a, 0x0a, 0x0e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x74,
	0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x37, 0x0a, 0x11, 0x48,
	0x75, 0x6d, 0x61, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x22, 0x0a, 0x05, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x52, 0x05, 0x68,
	0x75, 0x6d, 0x61, 0x6e, 0x22, 0x25, 0x0a, 0x0b, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x47, 0x65, 0x74,
	0x44, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x0e, 0x48,
	0x75, 0x6d, 0x61, 0x6e, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x22, 0x0a,
	0x05, 0x68, 0x75, 0x6d, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x73,
	0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x52, 0x05, 0x68, 0x75, 0x6d, 0x61,
	0x6e, 0x32, 0xbc, 0x02, 0x0a, 0x0c, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3b, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x15, 0x2e, 0x73,
	0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70,
	0x44, 0x74, 0x6f, 0x1a, 0x18, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61,
	0x6e, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x12,
	0x3b, 0x0a, 0x06, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x15, 0x2e, 0x73, 0x69, 0x67, 0x6d,
	0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x44, 0x74, 0x6f,
	0x1a, 0x18, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x08,
	0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61,
	0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x74,
	0x6f, 0x1a, 0x1a, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x12,
	0x3b, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x73, 0x69, 0x67, 0x6d,
	0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x74, 0x6f,
	0x1a, 0x18, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61, 0x6e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00, 0x12, 0x32, 0x0a, 0x03,
	0x67, 0x65, 0x74, 0x12, 0x12, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e, 0x48, 0x75, 0x6d, 0x61,
	0x6e, 0x47, 0x65, 0x74, 0x44, 0x74, 0x6f, 0x1a, 0x15, 0x2e, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x2e,
	0x48, 0x75, 0x6d, 0x61, 0x6e, 0x47, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x00,
	0x42, 0x40, 0x0a, 0x0d, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x69, 0x67, 0x6d,
	0x61, 0x42, 0x0a, 0x53, 0x69, 0x67, 0x6d, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x21, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6f,
	0x72, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x69, 0x67, 0x6d, 0x61, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData = file_packets_proto_rawDesc
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(file_packets_proto_rawDescData)
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_packets_proto_goTypes = []interface{}{
	(*Human)(nil),               // 0: sigma.Human
	(*Pending)(nil),             // 1: sigma.Pending
	(*Session)(nil),             // 2: sigma.Session
	(*HumanSignupDto)(nil),      // 3: sigma.HumanSignupDto
	(*HumanSignupOutput)(nil),   // 4: sigma.HumanSignupOutput
	(*HumanVerifyDto)(nil),      // 5: sigma.HumanVerifyDto
	(*HumanVerifyOutput)(nil),   // 6: sigma.HumanVerifyOutput
	(*HumanCompleteDto)(nil),    // 7: sigma.HumanCompleteDto
	(*HumanCompleteOutput)(nil), // 8: sigma.HumanCompleteOutput
	(*HumanUpdateDto)(nil),      // 9: sigma.HumanUpdateDto
	(*HumanUpdateOutput)(nil),   // 10: sigma.HumanUpdateOutput
	(*HumanGetDto)(nil),         // 11: sigma.HumanGetDto
	(*HumanGetOutput)(nil),      // 12: sigma.HumanGetOutput
}
var file_packets_proto_depIdxs = []int32{
	1,  // 0: sigma.HumanSignupOutput.pending:type_name -> sigma.Pending
	1,  // 1: sigma.HumanVerifyOutput.pending:type_name -> sigma.Pending
	0,  // 2: sigma.HumanVerifyOutput.human:type_name -> sigma.Human
	2,  // 3: sigma.HumanVerifyOutput.session:type_name -> sigma.Session
	0,  // 4: sigma.HumanCompleteOutput.human:type_name -> sigma.Human
	2,  // 5: sigma.HumanCompleteOutput.session:type_name -> sigma.Session
	0,  // 6: sigma.HumanUpdateOutput.human:type_name -> sigma.Human
	0,  // 7: sigma.HumanGetOutput.human:type_name -> sigma.Human
	3,  // 8: sigma.HumanService.signup:input_type -> sigma.HumanSignupDto
	5,  // 9: sigma.HumanService.verify:input_type -> sigma.HumanVerifyDto
	7,  // 10: sigma.HumanService.complete:input_type -> sigma.HumanCompleteDto
	9,  // 11: sigma.HumanService.update:input_type -> sigma.HumanUpdateDto
	11, // 12: sigma.HumanService.get:input_type -> sigma.HumanGetDto
	4,  // 13: sigma.HumanService.signup:output_type -> sigma.HumanSignupOutput
	6,  // 14: sigma.HumanService.verify:output_type -> sigma.HumanVerifyOutput
	8,  // 15: sigma.HumanService.complete:output_type -> sigma.HumanCompleteOutput
	10, // 16: sigma.HumanService.update:output_type -> sigma.HumanUpdateOutput
	12, // 17: sigma.HumanService.get:output_type -> sigma.HumanGetOutput
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_packets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Human); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pending); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Session); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanSignupDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanSignupOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanVerifyDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanVerifyOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanCompleteDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanCompleteOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanUpdateDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanUpdateOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanGetDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_packets_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HumanGetOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_packets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_rawDesc = nil
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
